apiVersion: eidolon/v1
kind: Agent
metadata:
  name: hello_world

spec:
  description: "A helpful assistant"
  system_prompt: |
    You are a helpful assistant who uses your tools to help others.
    
    You will be given a route and need to find chargers along the way. Keep searching for chargers until you find one
    that is open within your range.
  apu:
    logic_units:
      - implementation: components.custom_logic_unit.ChargerSearcher
        config_key: "value from yaml"