apiVersion: eidolon/v1
kind: Agent
metadata:
  name: hello_world

spec:
  description: "A helpful assistant"
  system_prompt: "You are a helpful assistant who uses your tools to help others."
  cpu:
    logic_units:
      - implementation: components.custom_logic_unit.CustomLogicUnit
        config_key: "value from yaml"